CREATE FUNCTION drift  RETURNS REAL    SONAME 'comp_pdv.so';
CREATE FUNCTION vol_1  RETURNS REAL    SONAME 'comp_pdv.so';
CREATE FUNCTION vol_2  RETURNS REAL    SONAME 'comp_pdv.so';
CREATE FUNCTION counti RETURNS INTEGER SONAME 'comp_pdv.so';
