CREATE AGGREGATE FUNCTION drift  RETURNS REAL    SONAME 'comp_pdv.so';
CREATE AGGREGATE FUNCTION vol_1  RETURNS REAL    SONAME 'comp_pdv.so';
CREATE AGGREGATE FUNCTION vol_2  RETURNS REAL    SONAME 'comp_pdv.so';
CREATE AGGREGATE FUNCTION counti RETURNS INTEGER SONAME 'comp_pdv.so';
