#! /usr/bin/python 
import config
import time 
import ao_db
import datetime as dt 

date_finish = '20180701'


def get_today_p2d():
    lt = time.localtime()
    date_today = str(lt.tm_year) + str(ds.d2s(lt.tm_mon)) + str(ds.d2s(lt.tm_mday))
    date_today_dt = ds.convert_str_date(date_today)
    date_today_p2d = date_today_dt + dt.timedelta(days=2)
    date_today_p2d_str = ds.convert_datetime_str(date_today_p2d)

    return date_today_p2d_str


# main routine, repeat forever 
while True:
    try: 
        ao_db.ao_db_run(dep_start=get_today_p2d(), dep_end=date_finish)
    except:  # if there is any mistake here, restart it again 
        ao_db.ao_db_run(dep_start=get_today_p2d(), dep_end=date_finish)
