#! /usr/bin/python 

import time
import ao_db
import datetime as dt
from datetime import date
import ds


# date when to finish the flight capture
date_finish = dt.date.today() + dt.timedelta(days=365)  # finish one day from today


def get_today_p2d():
    lt = time.localtime()
    date_today = str(lt.tm_year) + str(ds.d2s(lt.tm_mon)) + str(ds.d2s(lt.tm_mday))
    return ds.convert_str_date(date_today) + dt.timedelta(days=2)


def ao_db_run( dep_start : date
             , dep_end   : date
             , dest_l_choice  = 'USA'
             , dummy          = False
             , depth_max      = 2 ):
    """

    """

    # construct a set of already given pairs
    dep_date_l_dt = ds.construct_date_range(dep_start, dep_end)

    dest_l = {'all': ['JFK', 'LGA', 'EWR', 'SFO', 'LAX',
                      'BOS', 'FLL', 'MIA', 'DEN', 'ORD',
                      'HOU', 'IAH',
                      'ATL', 'DFW', 'CLT', 'LAS', 'PHX', 'SEA', 'MCO',
                      'MSP', 'DTW', 'PHL', 'BWI', 'DCA', 'MDW', 'SLC', 'IAD',
                      'SAN', 'HNL', 'TPA', 'PDX', 'DAL', 'STL', 'AUS', 'BNA', 'MSY',
                      'MCI', 'RDU', 'SNA', 'SJC', 'SMF', 'SJU', 'RSW', 'SAT', 'CLE',
                      'PIT', 'IND', 'CMH', 'MKE', 'BDL', 'MEX',  # up to here US
                      'PEK', 'DXB', 'HND', 'HKG', 'SIN', 'KUL',
                      'PVG', 'CGK', 'CAN', 'BKK', 'ICN', 'DEL',
                      'BOM', 'DEL', 'SHA', 'MNL', 'TPE', 'SZX', 'JED',
                      'CTU', 'KHI', 'KIX', 'GMP', 'HGH', 'CJU', 'SGN',
                      'THR', 'XIY', 'RUH', 'MAA',
                      # asia here
                      'LHR', 'CDG', 'IST', 'FRA', 'AMS', 'MAD', 'MUC', 'FCO',
                      'LGW', 'BCN', 'DME', 'SVO', 'ORY', 'AYT', 'CPH', 'ZRH',
                      'DUB', 'OSL', 'BRU', 'PMI', 'ARN', 'MAN', 'VIE', 'STN',
                      'DUS', 'TXL', 'LIS', 'MXP', 'ATH', 'HEL',
                      'VKO', 'GVA', 'HAM'  ]  # europe here
             , 'USA':  ['JFK', 'LGA', 'EWR',
                        'MIA', 'DEN', 'ORD',
                        'IAH',
                        'ATL', 'SAN']
             , 'asia': ['PEK', 'DXB', 'HND', 'HKG', 'SIN', 'KUL', 'PVG', 'CGK', 'CAN'] }

    ao_db.ao_db_fill( dep_date_l_dt
                    , dest_l[dest_l_choice]
                    , dummy     = dummy
                    , depth_max = depth_max )


# main routine, repeat forever
while True:
    try: 
        ao_db_run( dep_start = get_today_p2d()
                 , dep_end   = date_finish )
    except:  # if there is any mistake here, restart it again 
        ao_db_run( dep_start = get_today_p2d()
                 , dep_end   = date_finish )
